kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.NAME }}
  annotations:
    description: Exposes and load balances the application pods
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    name: {{ .Values.NAME }}